# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
##########################################################################
# This workflow will build a Java project with Gradle and
# cache/restore any dependencies to improve the workflow execution time
##########################################################################
name: 'Build and Test'
env:
  TZ: 'America/New_York'
  NODE_ENV: 'production'
  BABEL_ENV: 'production'
on:
  push:
    branches:
      - '*'

  pull_request:
    branches:
      - 'main'

#  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false
# Workflow Jobs
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: build
    steps:
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd $(find . -type d -name 'SmartScraper');
          export "REACT_APP_OPENAI_API_KEY=${{ secrets.REACT_APP_OPENAI_API_KEY }}";
          echo "NODE_ENV=${{ env.NODE_ENV }}" >> .env.production.local;
          echo "BABEL_ENV=${{ env.BABEL_ENV }}" >> .env.production.local;
          echo "GENERATE_SOURCEMAP=false" >> .env.production.local;
          npm install;
          npm run predeploy:github-pages;
        env:
          REACT_APP_OPENAI_API_KEY: ${{ secrets.REACT_APP_OPENAI_API_KEY }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository to pages
          path: 'SmartScraper/www'
          # Depending on branch protection rules, a  manually populated
          # `GITHUB_TOKEN_WORKAROUND` secret with permissions to push to
          # a protected branch must be used. This secret can have an arbitrary
          # name, as an example, you can use `SOME_RANDOM_TOKEN_STRING`.
          # Since this repository has no protected branches we will omit
          # this part of the step. end
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

